# Generated by Django 3.0.5 on 2020-09-10 13:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('loc', djongo.models.fields.JSONField()),
            ],
        ),
    ]
